arch:
  - amd64
  - ppc64le
language: python
python:
    - "3.5"
notifications:
    irc:
        - "chat.freenode.net#unary"
    email:
        - "admin@unary.ca"
env:
    - PYTHONPATH=./
install:
    - pip install tox
    - pip install coveralls
script:
    - python setup.py test
after_success:
    - coveralls
